---
title: "2016 In Review"
author: "Kristin Rollins"
date: "12/26/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(orfwx)
library(magrittr)
library(dplyr)
wxYear <- combineDataFrames(airportData, updatedData()) %>% 
  computeExtraDateVariables() %>% 
  filter(Year == 2016) %>%
  removeExtraDateVariables()
```

## Daily High Temperature

These are the ten **hottest** days of 2016, by daily high temperature.

```{r echo = FALSE}
wxYear %<>% mutate(Rank = as.integer(rank(-MaxTemperature)))
knitr::kable(
  top_n(wxYear, 10, MaxTemperature) %>%
    select(Rank, Date, MaxTemperature) %>%
    arrange(desc(MaxTemperature), desc(Date))
  )
```

These are the ten **coldest** days of 2016 (by daily high temperature)

```{r echo = FALSE}
wxYear %<>% mutate(Rank = as.integer(rank(MaxTemperature)))
knitr::kable(
  top_n(wxYear, -10, MaxTemperature) %>%
    select(Rank, Date, MaxTemperature) %>%
    arrange(MaxTemperature, desc(Date))
  )
```

## Daily Low Temperature

These are the ten **coldest** days of 2016, by daily low temperature.

```{r echo = FALSE}
wxYear %<>% mutate(Rank = as.integer(rank(MinTemperature)))
knitr::kable(
  top_n(wxYear, -10, MinTemperature) %>%
    select(Rank, Date, MinTemperature) %>%
    arrange(MinTemperature, desc(Date))
  )
```

These are the ten **hottest** days of 2016 (by daily low temperature).

```{r echo = FALSE}
wxYear %<>% mutate(Rank = as.integer(rank(-MinTemperature)))
knitr::kable(
  top_n(wxYear, 10, MinTemperature) %>%
    select(Rank, Date, MinTemperature) %>%
    arrange(desc(MinTemperature), desc(Date))
  )
```
